#!/bin/bash

# ⚠️  THIS FILE SHOWS THE EXACT COMMAND YOU NEED TO RUN
# It requires your Personal Access Token from GitHub

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║          MAX FITNESS - GitHub Push Instructions                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 YOUR SETUP IS READY!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Repository: https://github.com/mohith182007/Max-Fitness.git"
echo "Branch: main"
echo "Files Ready: YES ✅"
echo ""
echo "🔐 TO AUTHENTICATE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token (classic)'"
echo "3. Select scopes: repo, admin:repo_hook"
echo "4. Copy the token"
echo ""
echo "📤 COMMAND TO RUN:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   cd /home/jack/work/maxgym"
echo "   git push -u origin main"
echo ""
echo "🔐 THEN ENTER:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   Username: mohith182007"
echo "   Password: [PASTE YOUR PERSONAL ACCESS TOKEN HERE]"
echo ""
echo "✅ AFTER SUCCESSFUL PUSH:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Check: https://github.com/mohith182007/Max-Fitness"
echo "2. You should see all your files"
echo "3. Then deploy to Vercel using QUICK_START.md"
echo ""
echo "════════════════════════════════════════════════════════════════"
